on:
  push:
    branches:
      - master
  schedule:
  # should run at midnight 20th day of each month
    - cron:  '0 0 1 * *'

name: update-count-tables

jobs:
  update-count-tables:
    runs-on: ubuntu-18.04
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"
    
    steps:
    
    - name: Install git lfs 
      run: | 
        sudo apt-get -y update
        sudo apt-get -y install git-lfs
        git lfs install
    
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true

    - uses: r-lib/actions/setup-r@master
      with:
        r-version: 4.0

    - uses: r-lib/actions/setup-pandoc@master
    
    - name: Install system libraries
      run: |
        sudo apt-get install libglpk-dev libxml2-dev libgmp-dev

    - name: Install dependencies
      run: |
        install.packages(c('BiocManager', 'remotes'))
        BiocManager::install(c('rmarkdown', 'prettydoc', 'ggplot', 'tidyverse', 'seandavi/BiocPkgTools'))
      shell: Rscript {0}

    - name: Process new counts
      run: rmarkdown::render("README.Rmd", output_file = "index.html")
      shell: Rscript {0}
      
    - name: commit updated tables
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html posts.rds
        git commit -m "`date +%B` update" || echo "No changes to commit"
        git push origin master || echo "No changes to commit"
      
